//
// Created by jantonio on 5/05/19.
//

#ifndef AGILITYCONTEST_SERIALCHRONOMETER_AJAX_MGR_H
#define AGILITYCONTEST_SERIALCHRONOMETER_AJAX_MGR_H

#endif //AGILITYCONTEST_SERIALCHRONOMETER_AJAX_MGR_H
