//
// Created by jantonio on 5/05/19.
//

#ifndef AGILITYCONTEST_SERIALCHRONOMETER_MAIN_H
#define AGILITYCONTEST_SERIALCHRONOMETER_MAIN_H

#ifdef AGILITYCONTEST_SERIALCHRONOMETER_MAIN_C
#define EXTERN extern
#else
#define EXTERN
#endif

EXTERN char *program_name;
#endif //AGILITYCONTEST_SERIALCHRONOMETER_MAIN_H
